### PR TITLE
improved mp3 detection

### LINKED ISSUE #139: Does not recognize mp3 type
Hi! I have mp3 file what does not recognize by filetype. [Link to file](https://cloud.mail.ru/public/Mm2X/cNDSeJBnr)
First three bytes in my file: `0xff 0xfa 0xe3`
I have tried to use [python-magic](https://github.com/ahupp/python-magic) and it recognized this file like `audio/mpeg`. Can you look into it please?

### PR DESCRIPTION
**Pull request by CatKasha**
fixes #139
references:
https://www.datavoyage.com/mpgscript/mpeghdr.htm
https://en.wikipedia.org/wiki/MP3#/media/File:Mp3filestructure.svg

### CODE REVIEW

**Comment by CatKasha** [comment]
cant pass flake8 tests, i give up, feel free to remove comments

**Comment by guigarfr** [comment]
You have the errors in the logs, just fix them and update the PR.

```
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:46:5: E129 visually indented line with same indent as next logical line
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:47:21: E117 over-indented
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:55:5: E129 visually indented line with same indent as next logical line
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:56:25: E117 over-indented
```

**Comment by CatKasha** [comment]
> You have the errors in the logs, just fix them and update the PR.

Yea i saw it, E117 error was added with latest commit and idk how to fix E129 without make it looks ugly

**Comment by CatKasha** [comment]
Yay, thanks @MikhailMurashov for fixing flake issues

**Comment by MikhailMurashov** [comment]
@guigarfr can we merge it?

**Comment by guigarfr** [comment]
well i'm not a reviewer in the project. just gave my oppinion but don't have any permissions to merge... I gues you'll need a reviewer or two that can merge.

If it was me, i would fixup all commits in just one (there are many "fix flake8" commits) before merging.

**Pull request merged**
