### PR TITLE
add support for elf

### PR DESCRIPTION
**Pull request by xiaolangyuxin**
add support for elf

### CODE REVIEW

**Comment by h2non** [comment]
Please, fix the CI build. There is a linter issue:
https://travis-ci.org/h2non/filetype.py/jobs/377604223#L533-L539

**Comment by ltrojana3d** [comment]
I've fixed the *very* minor linting issues...

https://github.com/ltrojana3d/filetype.py/commit/e4416f3749300513fd862b8fd51335c65d89a95d

please feel free to cerry pick from my repo or, close this PR and I'll re-open it from my fork...

**Comment by dosas** [comment]
Obsolete due to https://github.com/h2non/filetype.py/pull/74

**Comment by guigarfr** [comment]
Yup @h2non that was already merged in #74 you can decline this PR?

**Pull request closed without merging**
