### PR TITLE
Fix mimetype for Gif Images

### PR DESCRIPTION
**Pull request by liam-middlebrook**

### CODE REVIEW

**Comment by h2non** [comment]
Thanks!

**Comment by liam-middlebrook** [comment]
Yeah no problem! Would you be able to push to PyPi later today or in the next few days? If not I'll just manually point my requirements.txt in at my fork for now and then change it back once its up.

Thanks!

**Comment by h2non** [comment]
I'm traveling these days, but hopefully I can do that tomorrow.

**Comment by h2non** [comment]
`v0.1.4` is not available at PyPI registry.

**Pull request merged**
